name: Release Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Paths
      id: paths
      shell: bash
      run: |
        echo "build=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libmosquitto-dev libssl-dev

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -B ${{ steps.paths.outputs.build }} -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.paths.outputs.build }}

    - name: Strip
      run: strip ${{ steps.paths.outputs.build }}/mobcli

    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.paths.outputs.build }}/mobcli
